# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2ac3ecb03ede9c4719272d4c65719ec6"
name = "diamond-finder"
handle = "diamond-finder-1"
application_url = "https://jpg-translated-sociology-fabrics.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://jpg-translated-sociology-fabrics.trycloudflare.com/auth/callback",
  "https://jpg-translated-sociology-fabrics.trycloudflare.com/auth/shopify/callback",
  "https://jpg-translated-sociology-fabrics.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
