# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2ac3ecb03ede9c4719272d4c65719ec6"
name = "diamond-finder"
handle = "diamond-finder-1"
application_url = "https://lexmark-hills-comparable-designers.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://lexmark-hills-comparable-designers.trycloudflare.com/auth/callback", "https://lexmark-hills-comparable-designers.trycloudflare.com/auth/shopify/callback", "https://lexmark-hills-comparable-designers.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://lexmark-hills-comparable-designers.trycloudflare.com"
subpath = "api"
prefix = "apps"

[pos]
embedded = false
