name: Scheduled Diamond Refresh

on:
  schedule:
    # Run every 12 hours at 6 AM and 6 PM UTC
    - cron: '0 6,18 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  refresh-diamonds:
    runs-on: ubuntu-latest
    timeout-minutes: 120 # 2 hour timeout for large imports
    
    steps:
      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Import All Diamonds
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          echo "Starting scheduled diamond refresh using direct import script..."
          
          # Run the import script inside the Fly app
          fly ssh console -a diamond-finder -C "npm run import:all" || {
            echo "❌ Failed to run import script"
            exit 1
          }
          
          echo "✅ Import script completed"
          
      - name: Check Import Status
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          echo "Checking import status..."
          
          # Give it a moment for the status to update
          sleep 5
          
          # Check the import status
          fly ssh console -a diamond-finder -C "npm run import:status" || {
            echo "❌ Failed to check import status"
            exit 1
          }
          
      - name: Notification
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "🎉 Scheduled diamond refresh completed successfully"
            echo "✅ All diamonds have been imported to the database"
          else
            echo "⚠️ Scheduled diamond refresh failed"
            echo "❌ Please check the logs for error details"
          fi